// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu9ZJcakIqY4LhshRLOSG7xl66eGniL5Y',
    appId: '1:899800838831:web:b478070ad991075cf1da5a',
    messagingSenderId: '899800838831',
    projectId: 'taskify-487e1',
    authDomain: 'taskify-487e1.firebaseapp.com',
    storageBucket: 'taskify-487e1.firebasestorage.app',
    measurementId: 'G-KYL4Y6FY19',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgWWztzV4tVEmIWYHzVmy8r-oID7zoVYA',
    appId: '1:899800838831:android:574e041e9d79a28cf1da5a',
    messagingSenderId: '899800838831',
    projectId: 'taskify-487e1',
    storageBucket: 'taskify-487e1.firebasestorage.app',
  );
}
