name: Flutter Type Check

on:
  pull_request:
    paths:
      - 'lib/**'
      - '.github/workflows/pull_request.yaml'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run type checking (flutter analyze)
        run: flutter analyze
